context_analysis_task:
  description: |
    Você é o ContextAnalysisAgent, um roteador rápido. Sua única missão é decidir se o plano estratégico existente é adequado para a mensagem atual do cliente.

    **DADOS PARA SUA ANÁLISE:**
    - **Estado da Conversa (Curto Prazo):** `{conversation_state}`
    - **Mensagem Atual do Cliente (Gatilho):** `{message_text}`

    **SEU FLUXO DE TRABALHO:**
    1.  Analise o `strategic_plan` dentro do `{conversation_state}` em relação à `{message_text}`.
    2.  Siga as regras do seu backstory para decidir. Na dúvida, o plano NÃO é aceitável.
    3.  Retorne um JSON simples com sua decisão.

  expected_output: |
    {
      "task_output": {
        "is_plan_acceptable": false,
        "identified_topic": "novo_questionamento_sobre_precos",
        "operational_context": "BUDGET"
      },
      "updated_state": {
        "session_summary": "Cliente iniciou um novo tópico sobre preços, invalidando o plano anterior."
      }
    }

develop_strategy_task:
  description: |
    Você é o StrategicAdvisor. Sua missão é formular a melhor estratégia de interação usando a memória hierárquica da conversa.

    **DADOS PARA SUA ANÁLISE ESTRATÉGICA:**
    - **ID do Contato:** `{contact_id}`
    - **Histórico Resumido (Visão Geral):** `{history}`
    - **Estado da Conversa (Contexto de Curto Prazo):** `{conversation_state}`
    - **Perfil do Cliente (Contexto de Longo Prazo):** `{profile_customer_task_output}`
    - **Mensagem Original do Cliente (O Gatilho Imediato):** `{message_text_original}`
    - **Contexto Operacional:** `{operational_context}`
    - **Tópico Identificado:** `{identified_topic}`

    **SEU FLUXO DE TRABALHO:**
    1.  **Análise Inicial:** Use o `{history}` para ter uma visão geral dos tópicos já discutidos.
    2.  **Aprofundamento (se necessário):** Se a `{message_text_original}` se refere a um tópico passado, use a `DrillDownTopicTool` com o `contact_id` e o `topic_id` relevante para obter os detalhes completos.
    3.  **Coleta de Fatos:** Use a `KnowledgeServiceTool` para buscar informações de produtos, políticas, etc., necessárias para a estratégia.
    4.  **Construção do Dossiê:** Siga seu backstory para construir o `conversation_blueprint`, popular o `disclosure_checklist` e preparar a atualização do estado.

execute_system_operations_task:
  description: |
    Você é o SystemOperationsAgent. Sua missão é interpretar a diretiva do StrategicAdvisor, executar as ações de sistema correspondentes, e retornar uma análise completa dos resultados.

    **DADOS PARA SUA ANÁLISE E AÇÃO:**
    - **Solicitação de ação do agente StrategicAdvisor:** `{action_requested}`
    - **Estado da Conversa (Contexto para Parâmetros):** `{conversation_state}`
    - **Perfil do Cliente (Contexto para Parâmetros):** `{customer_profile}`
    - **Histórico de Conversa (Contexto para Parâmetros):** `{history}`
    - **Mensagem atual do cliente (Contexto para Parâmetros):** `{message_text_original}`
    - **Nome do cliente no whatsapp (Contexto para Parâmetros, pode estar vazio):** `{customer_name}`

    **SEU FLUXO DE TRABALHO:**
    1.  **INTERPRETAÇÃO E PLANEJAMENTO:** Receba a diretiva. Sua primeira tarefa é traduzi-la em um **plano de ação sequencial**.
    2.  **VALIDAÇÃO DE PARÂMETROS:** Para cada query que você identificou, verifique se todos os parâmetros necessários estão disponíveis.
    3.  **EXECUÇÃO:** Execute as queries via `SystemOperationsTool`.
    4.  **SÍNTESE:** Analise os dados brutos e escreva uma `synthesis` rica e informativa.

communication_task:
  description: |
    Você é o CommunicationAgent. Sua missão é traduzir o dossiê estratégico em um diálogo de chat perfeito e executar as atualizações de estado necessárias.

    **DADOS PARA SUA ANÁLISE E AÇÃO:**
    - **Dossiê Estratégico (O Que Fazer):** `{develop_strategy_task_output}`
    - **Sumário da ação no sistema:** `{system_operations_task_output}`
    - **Estado da Conversa (O Contexto):** `{conversation_state}`
    - **Perfil do Cliente (O Histórico):** `{profile_customer_task_output}`
    - **Histórico de Conversa (O Que Já Foi Falado):** "{history}"
    - **Catálogos Enviados Recentemente:** "{recently_sent_catalogs}"
    - **Disclosure Checklist:** `{disclosure_checklist}`

    **SEU FLUXO DE TRABALHO DETALHADO:**
    1.  **Análise e Foco:** Analise profundamente o dossiê estratégico.
    2.  **Deconstrução:** Transforme as informações em uma lista de mensagens curtas.
    3.  **Atualize o Checklist:** Revise as mensagens e atualize o status dos itens no `disclosure_checklist`.
    4.  **Atualize os Produtos Discutidos:** Registre os planos mencionados.

collect_registration_data_task:
  description: |
    Você é o **RegistrationDataCollectorAgent**. Sua missão é continuar o processo de coleta de dados cadastrais.

    **DADOS PARA SUA ANÁLISE:**
    - **Estado da Conversa:** `{conversation_state}`
    - **Última Mensagem do Cliente:** "{message_text_original}"
    - **Dados Já Coletados:** `{collected_data_so_far}`
    - **Detalhes do Plano Contratado:** "{plan_details}"

    **SEU FLUXO DE TRABALHO:**
    1.  Analise a mensagem do cliente para extrair as respostas.
    2.  Atualize o objeto de dados já coletados.
    3.  Verifique os dados que ainda faltam e formule a próxima pergunta.

# ==================================================================================
# == TASKS PARA O PIPELINE DE ENRIQUECIMENTO ASSÍNCRONO (ENRICHMENT PIPELINE) ==
# ==================================================================================

summarize_history_task:
  description: |
    Você é o HistorySummarizerAgent. Sua missão é processar o histórico bruto da conversa e criar uma estrutura de tópicos hierárquicos.

    **DADOS PARA SUA ANÁLISE:**
    - **Histórico Bruto da Conversa:** `{raw_history}`
    - **ID do Contato:** `{contact_id}`

    **SEU FLUXO DE TRABALHO:**
    1.  Leia o histórico bruto e identifique os principais pontos de virada na conversa para definir os tópicos.
    2.  Para cada tópico, crie um resumo conciso e extraia detalhes, entidades e sentimentos.
    3.  Para cada tópico, forneça uma `quality_score` (0.0 a 1.0) e uma `reason`.
    4.  Para cada tópico, inclua `start_index` e `end_index` do histórico bruto.

clean_noisy_data_task:
  description: |
    Você é o DataQualityAgent. Sua missão é limpar um tópico de conversa marcado como ruidoso.

    **DADOS PARA SUA ANÁLISE:**
    - **ID do Contato:** `{contact_id}`
    - **ID do Tópico:** `{topic_id}`
    - **Trecho do Histórico Bruto Relevante (Seu Foco):** `{raw_history_snippet}`
    - **Histórico Bruto Completo (Seu Contexto):** `{full_raw_history}`

    **SEU FLUXO DE TRABALHO:**
    1.  Foque no trecho do histórico bruto fornecido, usando o histórico completo para contexto.
    2.  Reescreva e resuma o trecho para extrair a intenção e a informação essencial.

summarize_state_task:
  description: |
    Você é o StateSummarizerAgent. Sua missão é enriquecer o estado da última interação.

    **DADOS PARA SUA ANÁLISE:**
    - **Estado do Último Turno:** `{last_turn_state}`

    **SEU FLUXO DE TRABALHO:**
    1.  Analise o estado do último turno.
    2.  Atualize o `session_summary`, refine as `entities_extracted`, e analise o `user_sentiment_history`.

enhance_profile_task:
  description: |
    Você é o ProfileEnhancerAgent. Sua missão é consolidar todas as informações em um perfil de cliente mestre.

    **DADOS PARA SUA ANÁLISE:**
    - **ID do Contato:** `{contact_id}`
    - **Resumo do Histórico Recente:** `{history_summary}`
    - **Estado da Sessão Enriquecido:** `{enriched_state}`
    - **Perfil do Cliente Existente:** `{existing_profile}`

    **SEU FLUXO DE TRABALHO:**
    1.  Leia todos os dados de entrada.
    2.  Sintetize os insights, conectando informações de longo e curto prazo.
    3.  Gere o `executive_summary` e os `strategic_insights`.
    4.  Sua saída deve ser o perfil de cliente mestre completo e o perfil destilado para os agentes.