triage_initial_message_task:
  description: |
    Você é o TriageAgent. Analise a mensagem do cliente fornecida no input e seu histórico de cinversação:
    - Mensagem: "{message_text}"
    - ID Contato: "{contact_id}"
    - Timestamp: "{timestamp}"

    Histórico de conversação (10 ùltimas):

    "{history}"

    Siga seu FLUXO DE ANÁLISE E DECISÃO:
    1. Consulte caches L0/L1 - (Um dicionário com interações iguais a que recebeu agora).
    2. Consulte a Base de Conhecimento L2 - Qdrant (Uma coleção no qdrant que serve como uma memória no seu cerebro, feita para armazenar mensagens rápidas e embasadas no contexto. Criada por sua equipe especializada.).
    3. Decida se uma RESPOSTA IMEDIATA é viável. **Esta decisão exige MUITA CAUTELA.**
       - **Analise profundamente a MENSAGEM ATUAL do cliente em conjunto com o HISTÓRICO de conversação e o conteúdo das respostas encontradas em L0/L1/L2.**
       - **Para definir "action": "RESPONDED_DIRECTLY", AS SEGUINTES CONDIÇÕES DEVEM SER ABSOLUTAMENTE SATISFEITAS:**
         a. A resposta cacheada (de L0/L1 ou L2) é uma **correspondência exata ou de altíssima relevância semântica** para a pergunta/solicitação específica da mensagem atual.
         b. A resposta cacheada **resolve COMPLETAMENTE a necessidade expressa na mensagem atual**, sem necessitar de contexto adicional ou esclarecimentos.
         c. A pergunta do cliente é **simples e direta** (ex: uma pergunta factual, uma solicitação de informação básica já catalogada).
         d. O **histórico da conversa NÃO sugere** que o cliente está em um fluxo mais complexo, que já passou por essa informação, ou que a necessidade é uma variação sutil não coberta pela resposta cacheada.
       - **SE HOUVER QUALQUER DÚVIDA, ambiguidade, necessidade de interpretação mais profunda, ou se a mensagem atual tiver nuances não totalmente cobertas por uma resposta pronta, VOCÊ DEVE OPTAR POR "INITIATE_FULL_PROCESSING".** É melhor encaminhar para uma análise completa do que arriscar uma resposta direta inadequada.
       - Se, e somente se, todas as condições (a-d) forem rigorosamente atendidas, defina "action": "RESPONDED_DIRECTLY". (O sistema utilizará a melhor correspondência de cache que você identificou como base para a resposta).
    4. Se as condições estritas para resposta imediata não forem atendidas, determine a INTENÇÃO PRINCIPAL, TÓPICO e CONTEXTO OPERACIONAL.
       - Defina "action": "INITIATE_FULL_PROCESSING".

    L1/L0 - (Interações iguais a essa):

    "{l0l1_cache}"

    L2 - (Memória de mensagens imediatas para serem enviadas):

    "{l2_cache}"


    Retorne APENAS um objeto JSON com os campos especificados na sua SAÍDA ESPERADA.
  expected_output: |
    {
      "action": "RESPONDED_DIRECTLY" | "INITIATE_FULL_PROCESSING",
      "identified_topic": "identified_topic", # Deve ser preenchido mesmo para RESPONDED_DIRECTLY, se possível, para logging/análise
      "operational_context": "operational_context", # Deve ser preenchido mesmo para RESPONDED_DIRECTLY, se possível
    }


profile_customer_task:
  description: |
    Você é o CustomerProfiler. O TriageAgent decidiu por "INITIATE_FULL_PROCESSING".
    Dados recebidos (contexto da tarefa anterior):
    - ID Contato: "{contact_id}" (Extraído do output da tarefa de triagem)
    - Mensagem Original: "{message_text_original}" (Extraído do output da tarefa de triagem)
    - Contexto Operacional: "{operational_context}" (Extraído do output da tarefa de triagem)

    Siga seu FLUXO DE CONSTRUÇÃO DE PERFIL:
    1. Analise o perfil do cliente que será proporcionado a você abaixo.
    2. Se o perfil não existir, crie um novo perfil com base na mensagem original e no histórico, tente inferir informações relevantes.
    3. Se o perfil já existir, atualize-o com as informações da mensagem original e do histórico.
    4. Consolide as informações em um sumário e perfil detalhado.
       - Inclua compras passadas, tickets de suporte, sentimento atual, estágio de vendas e preferências.
    5. resuma o histórico de conversa para transmitir corretamente o contexto atual em comparação com o panorama geral da conversa.

    Perfil (pode ser null):

    "{customer_profile}"

    Histórico recente de conversas:

    "{history}"
    
    Retorne APENAS um objeto JSON com os campos especificados na sua SAÍDA ESPERADA.
  expected_output: |
    {
      "contact_id": ID do contato,
      "profile_summary": Sumário do perfil,
      "detailed_profile": { "past_purchases": [], "support_tickets": [], "current_sentiment": "...", "sales_stage": "...", "preferences": [] },
      "operational_context": (SALES, SUPPORT, etc.),
      "chat_history_summary": "summary of the chat history provided"
    }

develop_strategy_task:
  description: |
    Você é o StrategicAdvisor. Dados recebidos (contexto das tarefas anteriores):
    - Perfil do Cliente (JSON): "{profile_customer_task_output}"
    - Mensagem Original do Cliente: "{message_text_original}"
    - Contexto Operacional: "{operational_context}"
    - Tópico Identificado: "{identified_topic}"

    Siga sua FILOSOFIA DE CONSULTORIA ESTRATÉGICA e FLUXO DE DEFINIÇÃO DE ESTRATÉGIA:
    1. Analise todos os inputs.
    2. Use a BusinessGuidelinesTool para buscar as diretrizes relevantes para o contexto operacional.
    3. Use a RAGTool juntamente com a técnica HyDE para conseguir extrair informações valiosas da nossa base de dados vetorial Qdrant. 
    4. Formule o plano estratégico (objetivo, pontos-chave, perguntas, necessidade de ação de sistema).
       - Adapte a estratégia se o contexto for SALES (Alessandro) ou SUPPORT (Sofia).

    Retorne APENAS um objeto JSON com os campos especificados na sua SAÍDA ESPERADA.
  expected_output: |
    {
      "strategy_type": (ex: "SALES_QUALIFICATION", "SUPPORT_TROUBLESHOOTING"),
      "conversation_goal": Descrição do objetivo,
      "key_talking_points": [argumentos/informações],
      "questions_to_ask_client": [perguntas],
      "system_action_request": { "action_type": "...", "parameters": {...} } ou null,
      "internal_notes_for_craftsman": "Instruções de tom, estilo, foco.",
      "empathy_statement_suggestion": (Opcional, para Suporte) "Sugestão de frase empática inicial.",
      "super_message": (OBRIGATÓRIO) "Uma super mensagem de muitos parágrafos rica em informação para ser meticulosamente usada pelo ResponseCraftsman"

    }

execute_system_operations_task:
  description: |
    Você é o SystemOperationsAgent. Dados recebidos (contexto da tarefa anterior):
    - Solicitação de Ação de Sistema (JSON): "{develop_strategy_task.output.system_action_request}"

    Verifique se `system_action_request` não é nulo e contém `action_type` e `parameters`.
    Se for nulo ou inválido, retorne: {"action_type_executed": "NONE", "status": "no_action_requested", "data": null, "error_message": null}

    Caso contrário, siga seu FLUXO DE EXECUÇÃO DE AÇÃO DE SISTEMA:
    1. Mapeie o `action_type` para a ferramenta InternalAPITool_* correta.
    2. Execute a ferramenta com os `parameters`.
    Retorne APENAS um objeto JSON com os campos especificados na sua SAÍDA ESPERADA.
  expected_output: |
    {
      "action_type_executed": O `action_type` que foi processado,
      "status": "success" ou "error",
      "data": { ...dados retornados pela API... } (se sucesso),
      "error_message": "Detalhes do erro" (se error)
    }

craft_response_task:
  description: | # - Resultado da Ação de Sistema (JSON, pode ser nulo): "{execute_system_operations_task.output}"
    Você é o ResponseCraftsman, você trabalha numa empresa de rastreamento veícular chamada Global System Rastreamento. 
     
    Dados recebidos (contexto das tarefas anteriores):
    - Plano Estratégico (JSON): 
    
    "{develop_strategy_task_output}"

    - Perfil do Cliente (JSON): 
    
    "{profile_customer_task_output}"
    
    - Contexto Operacional: "{operational_context}"
    - Tópico Identificado: "{identified_topic}"
    - Mensagem Original do Cliente: "{message_text_original}"
     
    Siga seus PRINCÍPIOS DE COMUNICAÇÃO GLOBAL SYSTEM e FLUXO DE CRIAÇÃO DE RESPOSTA:
    1. Analise todos os inputs, especialmente as "internal_notes_for_craftsman" do plano estratégico.
    2. Gere as mensagens principais, **seguindo estritamente a diretriz de que cada mensagem deve ter entre 1 a 5 frases para garantir a legibilidade em um chat.**
        * **Objetivo Principal:** Criar um fluxo conversacional que seja fácil de ler e responder em um chat.
        * **Variação Controlada:** Dentro da faixa de 1-5 frases, varie o comprimento para soar natural. Por exemplo, uma sequência pode ser: 2 frases, depois 4 frases, depois 1 frase.
        * **Não Crie Blocos de Texto:** Se uma ideia, para ser completa, precisar de mais do que ~5 frases, você DEVE dividi-la em múltiplas mensagens sequenciais, cada uma respeitando o limite de 1-5 frases.
        * **A prioridade é a experiência do cliente no chat:** Mensagens muito longas são difíceis de acompanhar e desencorajam a interação.
    3. Gere conteúdo proativo (perguntas/respostas) para a Base de Conhecimento.
       (Este conteúdo será passado para a SaveFastMemoryMessages pela lógica do CrewAI após sua tarefa,
        você apenas gera o conteúdo no formato esperado).
    4. Se o `super_message` estiver presente, use-o como base para criar uma resposta rica e informativa. **Ao fazer isso, desmembre o conteúdo da `super_message` em segmentos lógicos, onde cada segmento resulte em uma mensagem de 1 a 5 frases.**
    5. Tente focar as informações recebidas na mensagem do cliente, no contexto e no tópico identificado para criar mensagens relevantes para o que o cliente precisa.
    6. IMPORTANTE: NUNCA SE APRESENTE! Seu Nome é colocado na mensagem ao ser enviada.
     
    Retorne APENAS um objeto JSON com "primary_messages_sequence" e "proactive_content_generated", NADA MAIS!.
  expected_output: |
    {
      "primary_messages_sequence": [ 
        "Mensagem 1 (ex: 2 frases).", 
        "Mensagem 2 (ex: 3 frases, continuando a ideia ou apresentando novo ponto).", 
        "Mensagem 3 (ex: 1 frase, talvez uma pergunta curta)." 
      ],
      "proactive_content_generated": [ {"question": "Como funciona o bloqueio do rastreador em área sem sinal?, answer: O rastreador armazena o comando"... }, ... ],
    }